default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3

#default: &default
#  adapter: mysql2
#  encoding: utf8
#  timeout: 5000
#  pool: 5
#  username: root
#  socket: /var/run/mysqld/mysqld.sock
#
#development:
#  <<: *default
#  database: skillz_development
#
#test:
#  <<: *default
#  database: skillz_test
#
#production:
#  adapter: postgresql
#  encoding: unicode
#  database: skillzz_production
#  username: skillzz
#  password: <%= ENV['SKILLZZ_DATABASE_PASSWORD'] %>
