default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: skillzz_development

test:
  <<: *default
  database: skillzz_test

production:
  <<: *default
  database: skillzz_production
  username: skillzz
  password: <%= ENV['SKILLZZ_DATABASE_PASSWORD'] %>